version: "3"
services:
  frontend:
    image: veikkoni/lahjarinki/frontend:${LAHJARINKI_VERSION}
    build: ./frontend/
    networks:
      - internal
    env_file:
      - .env
    ports:
      - "${LAHJARINKI_PORT}:80"

  backend:
    image: veikkoni/lahjarinki/backend:${LAHJARINKI_VERSION}
    build: ./backend/
    networks:
      - internal
    env_file:
      - .env

networks:
  internal:
