version: "3"
services:
  frontend:
    image: lahjarinki/frontend:${LAHJARINKI_TAG}
    container_name: lahjarinki_frontend
    build: ./frontend/
    networks:
      - internal
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:80"

  backend:
    image: lahjarinki/backend:${LAHJARINKI_TAG}
    container_name: lahjarinki_backend
    networks:
      - internal
    build: ./backend/
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
