version: "3"
services:
  frontend:
    image: veikkoni/lahjarinki/frontend:${LAHJARINKI_VERSION}
    build: ./frontend/
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:80"

  backend:
    image: lahjarinki/backend:${LAHJARINKI_TAG}
    build: ./backend/
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
