version: "3"
services:
  frontend:
    image: veikkoni/lahjarinki/frontend:dev
    build: ./frontend/
    networks:
      - internal
    ports:
      - "8080:80"

  backend:
    image: veikkoni/lahjarinki/backend:dev
    build: ./backend/
    networks:
      - internal

networks:
  internal:
# Add local mounts
