version: "3"
services:
  frontend:
    image: veikkoni/lahjarinki/frontend:${LAHJARINKI_VERSION}
    build: ./frontend/
    networks:
      - lahjarinki-internal
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:80"

  backend:
    image: lahjarinki/backend:${LAHJARINKI_TAG}
    build: ./backend/
    networks:
      - lahjarinki-internal
    env_file:
      - .env
